### ISSUE TITLE
What is the alternative APIs to use when the GetCurrentConditionsForStation does not have a current temp value?

### ISSUE THREAD

**Issue by davefxy** [keanenfarr/NationalWeatherServiceLibrary#3]
This is not a bug report. This is a question about the results returned.
Is there another set of NWS APIs to use when the GetCurrentConditionsForStation request returns no value for current temperature?
When I attempt to get the current temperature for i.e. Avon, Colorado, I frequently fail to see a value for TemperatureFahrenheit. Is there another service API I can use to obtain a locations current temperature?

**Comment by keanenfarr** [comment]
I believe there are other endpoints in the API that you can get other forecasts from other stations. But I don't recall what they are. This library only supports endpoints recommended by the NWS for the latitude and longitude entered.
