### ISSUE TITLE
The https://api.weather.gov/points/... response recently changed 2 properties : updateTie & Icon

### ISSUE THREAD

**Issue by davefxy** [keanenfarr/NationalWeatherServiceLibrary#4]
The response to the https://api.weather.gov/points/... recently changed 2 properties : updateTie & Icon.
The Icon property changed from a complete Url to a string that no longer a complete Url, it no longer has a website.
The updateTime property changed from a DateTime object to a Date Time string.
So now the NationalWeatherServiceLibrary library no longer works.
Am I observing this correctly?

**Comment by keanenfarr** [comment]
Yes. You are correct. I have updated the library with those changes.
